title: CMU Student
description: > # this means to ignore newlines until "baseurl:"
  Blog <br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yifansu1301.github.io" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Yifan'
  last_name: 'Su'
  cv: '/assets/pdf/Resume (2.22).pdf'
  avatar: '/images/personal.jpg'
  github_username:  YifanSu1301  
  email: yifansu@andrew.cmu.edu
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown
kmarkdown:
  input: GFM

permalink: /:categories/:year/:title.html


